######################################################################
# Automatically generated by qmake (2.01a) Di. Feb 9 15:24:41 2021
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT-=gui
# Input
HEADERS += x2gowswrapper.h
SOURCES += main.cpp x2gowswrapper.cpp
